### ISSUE TITLE
Error while using on java 8

### ISSUE THREAD

**Issue by gveronica86** [dwagelaar/jar2uml#1]
Hi
getting the following error:
Invalid byte tag in constant pool: 18

Is it compatible with java 8?

**Comment by dwagelaar** [comment]
Probably not: Jar2UML currently uses Apache BCEL 5.2.0, which is old. It should likely be ported to [BCEL 6.2](http://www-us.apache.org/dist//commons/bcel/RELEASE-NOTES.txt).

**Comment by dwagelaar** [comment]
Started branch https://github.com/dwagelaar/jar2uml/tree/bcel62

**Comment by dwagelaar** [comment]
Branch merged

**Comment by dwagelaar** [comment]
Included in release 2.0.0.
