### ISSUE TITLE
How to open the UML file

### ISSUE THREAD

**Issue by murthy-nn** [dwagelaar/jar2uml#5]
Using jar2uml, I have auto-generated .uml files for my Java project. How to open the uml file? Appreciate a response.

**Comment by dwagelaar** [comment]
The situation here has changed over the years, and this answer probably also has an expiry date. There used to be an Eclipse plug-in called [UML2Tools](https://www.eclipse.org/modeling/mdt/downloads/?project=uml2tools) that could automatically generate a UML class diagram (.umldi file) for a .uml model file, but this plug-in is no longer maintained. Another tool that used to be able to do is was [TOPCASED](https://topcased.gforge.enseeiht.fr/), but that has disappeared from the Internet entirely. Finally, Eclipse offers the [Papyrus](https://www.eclipse.org/papyrus/) UML editor, which can load your existing .uml file, but you still have to create your own class diagrams from it by dragging and dropping elements from your .uml model onto the diagram canvas. If you just want to browse the tree structure of the .uml model, then all you need is the [UML2](https://www.eclipse.org/modeling/mdt/?project=uml2) plug-in.

When you look at [Eclipse Marketplace](https://marketplace.eclipse.org/search/site/uml), you'll find some more tools that I don't have direct experience with. You'll need to try those out on your own.
